sudo: required
language: node_js
node_js:
  - "0.10.40"

before_install:
  - meteor || curl https://install.meteor.com | /bin/sh
  - npm install -g gagarin

services:
  - mongodb

cache:
  directories:
  - $HOME/.meteor

test: 
  - gagarin -v