language: node_js

node_js:
  - "0.12"

cache:
  directories:
  - $HOME/.meteor

before_install:
  - meteor || curl https://install.meteor.com | /bin/sh
  - npm install -g gagarin

services:
  - mongodb

script: 
  - gagarin -v